name: Build binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make android binaries
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: iptables-arm64
        path: build/local/arm64-v8a/iptables
    - uses: actions/upload-artifact@v3
      with:
        name: iptables-arm32
        path: build/local/armeabi-v7a/iptables
